USE [master]
GO

/****** Object:  Database [DB_ECG]    Script Date: 9/21/2025 11:26:46 PM ******/
CREATE DATABASE [DB_ECG]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DB_ECG', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\DB_ECG.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DB_ECG_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\DB_ECG_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DB_ECG].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DB_ECG] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DB_ECG] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DB_ECG] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DB_ECG] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DB_ECG] SET ARITHABORT OFF 
GO

ALTER DATABASE [DB_ECG] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DB_ECG] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DB_ECG] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DB_ECG] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DB_ECG] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DB_ECG] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DB_ECG] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DB_ECG] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DB_ECG] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DB_ECG] SET  ENABLE_BROKER 
GO

ALTER DATABASE [DB_ECG] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DB_ECG] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DB_ECG] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DB_ECG] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DB_ECG] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DB_ECG] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [DB_ECG] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DB_ECG] SET RECOVERY FULL 
GO

ALTER DATABASE [DB_ECG] SET  MULTI_USER 
GO

ALTER DATABASE [DB_ECG] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DB_ECG] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DB_ECG] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DB_ECG] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DB_ECG] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DB_ECG] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [DB_ECG] SET QUERY_STORE = ON
GO

ALTER DATABASE [DB_ECG] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [DB_ECG] SET  READ_WRITE 
GO

